#!/usr/bin/env python3
"""Q76 — protótipo reduzido de qubit de spin/circulação Hopf.

Classificação:
    teste de consistência operacional reduzido.

Este script verifica três blocos:
    1. projetores de eixo P_n^±;
    2. pesos Born operacionais p_±=(1±a·n)/2;
    3. erro de vazamento estimado por ||J||^2/Delta_gap^2.

Ele NÃO é simulação de hardware real. O objetivo é fixar a álgebra do
protótipo spin/Hopf antes de escolher um dispositivo físico.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parent
OUT = ROOT / "saida_simular_qubit_spin_hopf.md"


SIGMA_X = np.array([[0, 1], [1, 0]], dtype=complex)
SIGMA_Y = np.array([[0, -1j], [1j, 0]], dtype=complex)
SIGMA_Z = np.array([[1, 0], [0, -1]], dtype=complex)
IDENT = np.eye(2, dtype=complex)
SIGMAS = np.array([SIGMA_X, SIGMA_Y, SIGMA_Z])


def unit(v: np.ndarray) -> np.ndarray:
    n = np.linalg.norm(v)
    if n == 0:
        raise ValueError("zero vector")
    return v / n


def ndot_sigma(n: np.ndarray) -> np.ndarray:
    return n[0] * SIGMA_X + n[1] * SIGMA_Y + n[2] * SIGMA_Z


def projector(n: np.ndarray, sign: int) -> np.ndarray:
    return 0.5 * (IDENT + sign * ndot_sigma(n))


def rho_from_bloch(a: np.ndarray) -> np.ndarray:
    return 0.5 * (IDENT + ndot_sigma(a))


def rotation(n: np.ndarray, theta: float) -> np.ndarray:
    """SU(2) rotation generated by n.sigma."""
    return np.cos(theta / 2.0) * IDENT - 1j * np.sin(theta / 2.0) * ndot_sigma(n)


def bloch_from_rho(rho: np.ndarray) -> np.ndarray:
    return np.array([np.real(np.trace(rho @ s)) for s in SIGMAS])


def fidelity_pure_gate(u_target: np.ndarray, u_actual: np.ndarray) -> float:
    """Average process fidelity proxy for single qubit unitaries."""
    d = 2
    tr = np.trace(u_target.conj().T @ u_actual)
    return float((abs(tr) ** 2 + d) / (d * (d + 1)))


def main() -> None:
    # Preparação: estado com vetor de Bloch inclinado.
    a = unit(np.array([1.0, 1.0, 1.0]))
    axes = {
        "z": unit(np.array([0.0, 0.0, 1.0])),
        "x": unit(np.array([1.0, 0.0, 0.0])),
        "diag": unit(np.array([1.0, -1.0, 2.0])),
    }
    rho = rho_from_bloch(a)

    # Porta de teste: rotação pi/2 em torno de y. Simulamos erro de eixo
    # pequeno para representar imperfeição de contorno.
    y = unit(np.array([0.0, 1.0, 0.0]))
    y_tilt = unit(np.array([0.02, 1.0, -0.01]))
    theta = np.pi / 2.0
    u_ideal = rotation(y, theta)
    u_actual = rotation(y_tilt, theta)
    fid_gate = fidelity_pure_gate(u_ideal, u_actual)

    rho_after = u_actual @ rho @ u_actual.conj().T
    bloch_after = bloch_from_rho(rho_after)

    # Vazamento reduzido por acoplamento ao complemento.
    delta_gap = 1.0
    j_norms = [0.01, 0.03, 0.10, 0.30]

    lines = [
        "# Saída — Q76 protótipo spin/Hopf",
        "",
        "Classificação: teste de consistência operacional reduzido.",
        "",
        "## Projetores e pesos de leitura",
        "",
        f"- vetor de preparação $\\mathbf a$: `{a.tolist()}`",
        "",
        "| eixo do aparelho | p_plus GDQ/Born | p_minus GDQ/Born | soma |",
        "|---|---:|---:|---:|",
    ]

    for label, n in axes.items():
        p_plus = float(np.real(np.trace(rho @ projector(n, +1))))
        p_minus = float(np.real(np.trace(rho @ projector(n, -1))))
        lines.append(f"| {label} | {p_plus:.12f} | {p_minus:.12f} | {p_plus + p_minus:.12f} |")

    lines += [
        "",
        "## Porta por transporte de contorno",
        "",
        "Porta ideal: rotação $\\pi/2$ em torno de $y$.",
        "",
        f"- eixo real inclinado: `{y_tilt.tolist()}`",
        f"- fidelidade unitária reduzida: `{fid_gate:.12f}`",
        f"- Bloch após porta real: `{bloch_after.tolist()}`",
        "",
        "## Vazamento para complemento",
        "",
        "Estimador reduzido:",
        "",
        "$$",
        "\\epsilon_{\\rm leak}",
        "\\sim",
        "\\frac{\\|J\\|^2}{\\Delta_{\\rm gap}^2}.",
        "$$",
        "",
        f"- $\\Delta_{{\\rm gap}}={delta_gap:.6f}$",
        "",
        "| ||J|| | epsilon_leak |",
        "|---:|---:|",
    ]

    for j in j_norms:
        eps = (j / delta_gap) ** 2
        lines.append(f"| {j:.6f} | {eps:.12e} |")

    lines += [
        "",
        "## Interpretação",
        "",
        "O protótipo spin/Hopf recupera exatamente os pesos projetivos de",
        "Stern--Gerlach e fornece uma métrica reduzida para erro de porta e",
        "vazamento. A informação física que falta para virar previsão de hardware é",
        "$\\Delta_{\\rm gap}$, $J$ e a impedância de aparelho calculados pela Hessiana",
        "da ação oficial.",
        "",
        "$$",
        "\\boxed{",
        "\\text{qubit spin/Hopf fechado como redução operacional; hardware real permanece futuro.}",
        "}",
        "$$",
        "",
    ]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()

