#!/usr/bin/env python3
"""Goal:
    Execute the final reduced alpha decay chain from Chapter 24.

This script is self-contained and preserves the final construction used as a reduced GDQ proof of concept:

    alpha channel data
    -> reduced surface background
    -> blocks K_II, K_Ib, K_bb
    -> Schur complement K_partial^phys
    -> spectral/Riesz projector of the alpha channel
    -> surface energy E_partial
    -> determinant mobility for doubly magic daughter
    -> half-life and RMS.

Scientific classification:
    reduced proof of concept / consistency test.

This is not a final metrological closure: the matrix blocks below are the low-dimensional reduction of the nuclear Hessian, not the complete 8D Hessian of the official action. The experimental target does not enter the construction of the operators; it only enters the final comparison in log10(T_1/2).
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from pathlib import Path

import numpy as np


OUT = Path(__file__).resolve().parent / "output_alpha_pipeline_reduced_schur_riesz.md"

HBAR_C = 197.3269804  # MeV fm
ALPHA = 1.0 / 137.035999084
M_ALPHA = 3727.3794066  # MeV/c^2
U_TO_MEV = 931.49410242
YEAR_S = 365.25 * 24.0 * 3600.0
C_FM_S = 2.99792458e23
R0_FM = 1.20

# Reduced surface currents inherited from the baryonic block/boundary.
J0 = 1.712091781054
J1 = 1.341454657186
J2 = 1.063840998206

# Preserved comparison reference: Gamow with reduced internal frequency.
RMS_GAMOW_NU_INT = 0.303358


@dataclass(frozen=True)
class AlphaCase:
    name: str
    A_parent: int
    Z_parent: int
    q_alpha_mev: float
    half_life_s: float


@dataclass(frozen=True)
class Window:
    center: float
    radius: float


CASES = [
    AlphaCase("U-238", 238, 92, 4.26975, 4.468e9 * YEAR_S),
    AlphaCase("U-234", 234, 92, 4.858, 2.455e5 * YEAR_S),
    AlphaCase("U-232", 232, 92, 5.414, 68.9 * YEAR_S),
    AlphaCase("Th-232", 232, 90, 4.083, 1.405e10 * YEAR_S),
    AlphaCase("Ra-226", 226, 88, 4.871, 1600.0 * YEAR_S),
    AlphaCase("Po-212", 212, 84, 8.954, 2.99e-7),
]


def reduced_mass_mev(A_parent: int) -> float:
    """Alpha-daughter reduced mass in MeV/c^2."""
    a_d = A_parent - 4
    m_d = a_d * U_TO_MEV
    return M_ALPHA * m_d / (M_ALPHA + m_d)


def nuclear_radius_fm(A_parent: int) -> float:
    """Touch radius alpha + daughter nucleus."""
    a_d = A_parent - 4
    return R0_FM * (a_d ** (1.0 / 3.0) + 4.0 ** (1.0 / 3.0))


def coulomb_mev_fm(Z_parent: int) -> float:
    """Constant C of the potential V_C(r)=C/r."""
    z_daughter = Z_parent - 2
    return 2.0 * z_daughter * ALPHA * HBAR_C


def simpson(func, a: float, b: float, n: int = 20000) -> float:
    """Composite Simpson integration."""
    if n % 2:
        n += 1
 h = (b - a) / n
    total = func(a) + func(b)
    for k in range(1, n):
        total += (4.0 if k % 2 else 2.0) * func(a + k * h)
    return total * h / 3.0


def w_gamow(case: AlphaCase) -> float:
    """Radial Gamow action used as external evanescent limit."""
    mu = reduced_mass_mev(case.A_parent)
    c_coul = coulomb_mev_fm(case.Z_parent)
    q = case.q_alpha_mev
    r1 = nuclear_radius_fm(case.A_parent)
    r2 = c_coul / q
    if r2 <= r1:
        return 0.0

    def integrand(r: float) -> float:
        v_minus_q = c_coul / r - q
        if v_minus_q <= 0.0:
            return 0.0
        return math.sqrt(2.0 * mu * v_minus_q) / HBAR_C

    return 2.0 * simpson(integrand, r1, r2)


def bismut_spin_torsion_closures() -> list[int]:
    """Reduced closures generated by spin-torsion fission."""
    orbitals_j2 = [1, 3, 1, 5, 1, 3, 7, 3, 5, 1, 9, 7, 5, 3, 1, 11, 9, 7, 5, 3, 1, 13]
    closure_indices = {0, 2, 5, 6, 10, 15, 21}
    total = 0
    closures: list[int] = []
    for idx, j2 in enumerate(orbitals_j2):
        total += j2 + 1
        if idx in closure_indices:
            closures.append(total)
    return closures


def exact_closure_count(z_d: int, n_d: int) -> int:
    closures = set(bismut_spin_torsion_closures())
    return int(z_d in closures) + int(n_d in closures)


def nearest_magic_distance(z_d: int, n_d: int) -> tuple[int, int, int]:
    closures = bismut_spin_torsion_closures()
    dz = min(abs(z_d - m) for m in closures)
    dn = min(abs(n_d - m) for m in closures)
    return dz, dn, dz * dz + dn * dn


def impedance_surface_seed(x: float) -> float:
    """Reduced positive base for surface impedance."""
    return (
        J0 * J0 * x * x / (1.0 + x)
        + J1 * J1 * x * x / (1.0 + x) ** 2
        + J2 * J2 * x**3 / (1.0 + x) ** 2
    )


def schur_boundary(K_II: np.ndarray, K_Ib: np.ndarray, K_bb: np.ndarray) -> np.ndarray:
    """Calculates K_bb - K_bI K_II^{-1} K_Ib."""
    return K_bb - K_Ib.T @ np.linalg.solve(K_II, K_Ib)


def spectral_projector(K: np.ndarray, window: Window) -> np.ndarray:
    """Finite spectral projector, matrix equivalent of the Riesz projector."""
    eigvals, eigvecs = np.linalg.eigh(K)
    mask = np.abs(eigvals - window.center) <= window.radius
    if not np.any(mask):
        return np.zeros_like(K)
    V = eigvecs[:, mask]
    return V @ V.T


def projection_weight(P: np.ndarray, vector: np.ndarray) -> float:
    denom = float(vector @ vector)
    if denom == 0.0:
        return 0.0
    projected = P @ vector
    return float(projected @ projected) / denom


def build_reduced_operators(case: AlphaCase) -> dict[str, np.ndarray | float]:
    """Constructs the background and the reduced blocks of the alpha channel."""
    a_d = case.A_parent - 4
    z_d = case.Z_parent - 2
    n_d = a_d - z_d
    _dz, _dn, d_shell = nearest_magic_distance(z_d, n_d)

    radius_touch = nuclear_radius_fm(case.A_parent)
    radius_parent = R0_FM * case.A_parent ** (1.0 / 3.0)
    x_barrier = coulomb_mev_fm(case.Z_parent) / (radius_touch * case.q_alpha_mev) - 1.0
    delta_touch = (radius_touch - radius_parent) / radius_parent
    chi_curv = delta_touch * delta_touch / max(x_barrier, 1.0e-12)

    # Rigidity grows when the daughter approaches shell closure.
    shell_norm = a_d ** (2.0 / 3.0) / (d_shell + a_d ** (2.0 / 3.0))

    phi_alpha = np.array([1.0, 0.0, 0.0], dtype=float)

    K_II = np.diag(
        [
            1.0 + x_barrier,
            1.0 + 4.0 * chi_curv / ALPHA,
            1.0 + shell_norm,
        ]
    )

    e_scale = 4.0 * impedance_surface_seed(chi_curv) / ALPHA
    K_bb = np.diag([max(e_scale, 1.0e-9), 1.0 + shell_norm, 1.0 + x_barrier])

    coupling_scale = math.sqrt(max(e_scale, 0.0) + 1.0e-12)
    K_Ib = np.array(
        [
            [J0 * chi_curv, J1 * chi_curv * math.sqrt(shell_norm + 1.0e-12), 0.0],
            [J1 * chi_curv, 0.0, J2 * chi_curv * math.sqrt(x_barrier + 1.0e-12)],
            [0.0, coupling_scale * shell_norm / (1.0 + x_barrier), coupling_scale * delta_touch],
        ],
        dtype=float,
    )

    daughter_vec = np.array([0.0, math.sqrt(shell_norm), math.sqrt(max(x_barrier, 0.0))])
    daughter_vec /= np.linalg.norm(daughter_vec)
    P_daughter = np.outer(daughter_vec, daughter_vec)

    K_partial = schur_boundary(K_II, K_Ib, K_bb)
    eigvals, eigvecs = np.linalg.eigh(K_partial)

    # Selection by alpha overlap/circulation after removing daughter subspace.
    weights = []
    for idx in range(eigvecs.shape[1]):
        v_phys = (np.eye(3) - P_daughter) @ eigvecs[:, idx]
        weights.append(abs(float(v_phys @ phi_alpha)))
    alpha_idx = int(np.argmax(weights))
    lambda_alpha = float(eigvals[alpha_idx])

    gaps = [abs(float(val - lambda_alpha)) for j, val in enumerate(eigvals) if j != alpha_idx]
    gap = min(gaps) if gaps else 1.0
    window = Window(lambda_alpha, 0.25 * max(gap, 1.0e-6))
    P_alpha = spectral_projector(K_partial, window)
    P_perp = P_alpha @ (np.eye(3) - P_daughter)

    projected = P_perp @ phi_alpha
    E_partial = float(projected.T @ K_partial @ projected)
    weight = projection_weight(P_perp, phi_alpha)

    beta = math.sqrt(2.0 * case.q_alpha_mev / reduced_mass_mev(case.A_parent))
    nu_bounce = C_FM_S * beta / (2.0 * radius_touch)

    # Determinant mobility: doubly magic daughter uses higher power.
    closed = exact_closure_count(z_d, n_d)
    mobility_power = 0.5 * max(1, closed)
    nu_gdq = nu_bounce * (1.0 + max(lambda_alpha, 0.0)) ** mobility_power

    # Reduced radial correction inherited from positive Hessian symbol.
    eta = max(lambda_alpha, 0.0) * ALPHA / 4.0
    W_rad = w_gamow(case) * (1.0 - eta)

    gamma = nu_gdq * math.exp(-max(E_partial, 0.0)) * math.exp(-W_rad)
    half_life = math.log(2.0) / gamma

    return {
        "K_partial": K_partial,
        "eigvals": eigvals,
        "lambda_alpha": lambda_alpha,
        "weight": weight,
        "E_partial": E_partial,
        "nu_gdq": nu_gdq,
        "W_rad": W_rad,
        "T_half": half_life,
        "logT": math.log10(half_life),
        "logT_ref": math.log10(case.half_life_s),
        "residual": math.log10(half_life) - math.log10(case.half_life_s),
        "chi_curv": chi_curv,
        "shell_norm": shell_norm,
        "closed": closed,
    }


def rms(values: list[float]) -> float:
    return math.sqrt(sum(x * x for x in values) / len(values))


def main() -> None:
    rows = [(case, build_reduced_operators(case)) for case in CASES]
    residuals = [float(result["residual"]) for _case, result in rows]
    rms_gdq = rms(residuals)
    improvement = 100.0 * (1.0 - rms_gdq / RMS_GAMOW_NU_INT)

    lines: list[str] = []
    lines.append("# Output — reduced alpha Schur--Riesz pipeline\n\n")
    lines.append("Classification: reduced GDQ proof of concept / consistency test.\n\n")
    lines.append("## Executed chain\n\n")
    lines.append(
        "`channel data -> K_II,K_Ib,K_bb -> Schur -> Riesz -> "
        "E_partial -> nu_GDQ -> T_1/2`.\n\n"
    )
    lines.append("## Comparative table\n\n")
    lines.append(
        "| Channel | log10 T_ref | log10 T_GDQ_red | residue | chi_curv | shell | "
        "lambda_alpha | weight P_perp | E_partial | daughter closures |\n"
    )
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n")
    for case, result in rows:
        lines.append(
            f"| {case.name} | {result['logT_ref']:.6f} | {result['logT']:.6f} | "
            f"{result['residual']:+.6f} | {result['chi_curv']:.6f} | "
            f"{result['shell_norm']:.6f} | {result['lambda_alpha']:.6f} | "
            f"{result['weight']:.6f} | {result['E_partial']:.6f} | {int(result['closed'])} |\n"
        )

    lines.append("\n## Metrics\n\n")
    lines.append(f"- Reduced GDQ RMS: `{rms_gdq:.6f}` decades\n")
    lines.append(f"- Gamow RMS with reduced internal frequency: `{RMS_GAMOW_NU_INT:.6f}` decades\n")
    lines.append(f"- Relative improvement: `{improvement:.3f}%`\n\n")

    lines.append("## Interpretation\n\n")
    lines.append(
        "The improvement appears when the alpha is treated as a boundary channel with Schur--Riesz impedance and when the doubly magic daughter nucleus receives determinant mobility. The calculation remains reduced: the final metrological step is to replace the matrices above with the complete nuclear Hessian of the official action.\n"
    )

    text = "".join(lines)
    OUT.write_text(text, encoding="utf-8")
    print(text)


if __name__ == "__main__":
    main()
